/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatSidebar: typeof import('./src/components/sidebar/ChatSidebar.vue')['default']
    Content: typeof import('./src/components/content/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sender: typeof import('./src/components/sender/index.vue')['default']
  }
}
